### PR TITLE
added -maxwarn option to grompp command of gmx solvate

### PR DESCRIPTION
**Pull request by thepineapplepirate**
this will allow users to override non-fatal warnings when solvating any given system.

### CODE REVIEW

**Comment by thepineapplepirate** [comment]
this submission includes the addition of -maxwarn to the tool, as well as bumping up version of galaxy from 0 to 1

**Review by simonbray — APPROVED** [review]
@thepineapplepirate can this be merged?

**Comment by thepineapplepirate** [comment]
yes sir, this one is ready :)

**Comment by simonbray** [comment]
thanks!

**Pull request merged**
