### PR TITLE
Solvate fix, add ndx file option to gmx_sim

### PR DESCRIPTION
**Pull request by simonbray**

### CODE REVIEW

**Comment by simonbray** [comment]
Notes:
- acpype tool currently failing on usegalaxy.eu since last version update
- (probably) need to split setup into separate pdb2gmx and editconf tools
- make ion adding optional in solvate tool

**Comment by bgruening** [comment]
> acpype tool currently failing on usegalaxy.eu since last version update

can you try this again, I think this was an installation error.

**Comment by simonbray** [comment]
No luck. I get the same message as before: `acpype: command not found`. But this doesn't need to be urgently fixed.

**Comment by simonbray** [comment]
@bgruening, can we merge this already (and install the new version onto usegalaxy.eu)? I will put the other things into an issue and continue to work on them. At least this will be enough to run the simulations we discussed with Steffen.

**Comment by bgruening** [comment]
Yes, I can do!

> AssertionError: Test file (index.ndx) is missing. If you use planemo try --update_test_data to generate one.

**Pull request merged**
