### PR TITLE
Add maintainers to .shed.yml files

### PR DESCRIPTION
**Pull request by simonbray**
I would like to improve the @planemo-autoupdate bot so it pings tool maintainers when making tool updates - to do this, I need to add information about maintainers to the .shed.yaml files.

@bgruening hope this looks like a good approach, I did not get much feedback on my tools-iuc issues. If this works out well I would try and push it there as well.

### CODE REVIEW

**Comment by bgruening** [comment]
Yes, this looks great to me!

**Comment by simonbray** [comment]
Can we merge this? Or should we wait for an OK from @chrisbarnettster and @tsenapathi

**Comment by bgruening** [comment]
Ok, to merge and fail the TS upload. It does not change the tools so that should be safe.

**Review by tsenapathi — APPROVED** [review]

**Review by chrisbarnettster — APPROVED** [review]

**Comment by simonbray** [comment]
@bgruening could you merge please?

**Comment by simonbray** [comment]
thanks!

**Pull request merged**
