### PR TITLE
Update tool versions

### PR DESCRIPTION
**Pull request by simonbray**

### CODE REVIEW

**Comment by bgruening** [comment]
Wonderful! If we are happy with github actions, we should remove travis.

I'm wondering if you are already using the automatic version bump? :)

**Comment by simonbray** [comment]
> Wonderful! If we are happy with github actions, we should remove travis.
Yes, fine with me.

> I'm wondering if you are already using the automatic version bump? :)
No, not at the moment. :( We need to talk about this again.

Btw, do not merge yet, I realised there is a new version of ambertools and acpype which can be added.

**Comment by simonbray** [comment]
Happy to merge now. How do I stop/remove the travis check? I thought this was dealt with in Chris' PR.

**Comment by chrisbarnettster** [comment]
> Happy to merge now. How do I stop/remove the travis check? I thought this was dealt with in Chris' PR.

I removed the integration but forgot the webhook - fixed now. Webhook deleted.

**Comment by simonbray** [comment]
> I removed the integration but forgot the webhook - fixed now. Webhook deleted.

Thank you - but I can still see the travis job in the list of checks for some reason?

**Comment by bgruening** [comment]
I think this is still because it is on the master branch. I would not worry about it until it is still there in the next PRs following this one.

**Comment by simonbray** [comment]
Can you force-merge this one then?

**Comment by simonbray** [comment]
Great, thank you!

**Pull request merged**
