### PR TITLE
added -maxwarn option to grompp command in gmx_solvate tool

### PR DESCRIPTION
**Pull request by thepineapplepirate**
it will be useful to also have this option when solvating systems.

### CODE REVIEW

**Comment by simonbray** [comment]
Can you bump the `@GALAXY_VERSION@` tokens please?

**Comment by thepineapplepirate** [comment]
ok will do, sorry i forgot about last part!

**Comment by simonbray** [comment]
No worries, is it ok to merge this PR and close the other two?

**Comment by thepineapplepirate** [comment]
I would close this one and merge the other gmx_solvate one (#134), which has both updates and was submitted a few hours ago, and passed the tests. Thanks Simon!

**Pull request closed without merging**
