### PR TITLE
Update em and energy tools

### PR DESCRIPTION
**Pull request by simonbray**
So we can provide a check of the potential in the tutorial.

### CODE REVIEW

**Comment by tsenapathi** [comment]
Can we also create a plot with this too?

**Comment by simonbray** [comment]
My idea is to use the Galaxy line plot visualization on the tabular tool, running it locally made something like this:
EM

**Comment by tsenapathi** [comment]
@simonbray Cool, make sense.

**Comment by simonbray** [comment]
Any idea how to get Travis running?

**Comment by bgruening** [comment]
It is running, but the status is not reported for some reasons: https://travis-ci.org/github/galaxycomputationalchemistry/galaxy-tools-compchem

**Comment by simonbray** [comment]
Thanks!

**Comment by bgruening** [comment]
We have a problem with the gromacs tools... the test-data directory is >70MB :(

**Pull request merged**
